#cloud-config
users:
  - default
  - name: renggli
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6xIWERIZ7yD6W3niuuJ8S8FMGm3YNy1J1yxLZb+KQjY9hwIEfWJSNDIi6bbKRB0ozo0ca5o4/GBYX/MtBrbvqiQMtviboUtr/vLXvVVuTwf8HIubwySbIEfPqrpqpvQQtzRGu1SaDIm0gmlqqWwV6ppRIdy0AQIQCL9rc8pNh8x/gwzWHKKG16suxvH3j+qD+5Du+/NT7ab1BmHqPMmUK1GId8/oUejVHIiK7mGRERoQwdI8sE1eLVNcCU/NYzvx/jLIqDT1+YKQaLOxkiJViCBttn/1xLvW33fEnuuBjFCpjwFtE3/qGbR4jWlOpWqevI6TLKyEbitWPZRVU0UwWI43vMZp5MRG+QVjx79P7nKf6BjUpuvC/KaWx2lIHz7lBig8hyRv40m9kjHuzEN3Yj5mSbZ/XJhFsT0PuQbk9E8EM0bqtHSpRi+OdDH8nHqbWFd45Q4pON1OwRwq4Gztb8i8+ZvaWGmWEAyvXIEimUB+fsoQPRhc9E4OmxTRnboM= andrin@DESKTOP-9HLUJS2



# Upgrade system
package_update: true
#package_upgrade: true

# Install needed packages
packages:
  - npm
  - nginx

#Make all commands which do not require sudo not to use sudo 
runcmd:
  - su - renggli -c "git clone https://gitlab.com/bbwrl/m346-ref-card-02"
  - cd m364-ref-card-02
  - npm install
  - npm update
  - npm audit fix --force
  - npm start

