#cloud-config
users:
  - default
  - name: renggli
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBAbDWKwQ8Fq58t2owBwr515esbsOVJBKdL+xt0tE3Lq andrin@DESKTOP-9HLUJS2

