#cloud-config
users:
  - default
  - name: renggli
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINYQXDMGRT3xdfpaTJwDNXPveToziVmVO02oqaVdmJgb andrin@DESKTOP-9HLUJS2

package_update: true
package_upgrade: true

runcmd:
  - sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  - sudo wget -q -O /usr/share/keyrings/grafana-archive-keyring.gpg https://packages.grafana.com/gpg.key
  - sudo apt-get update
  - sudo apt-get install grafana
  - sudo systemctl enable grafana-server
  - sudo systemctl start grafana-server
  - wget https://github.com/prometheus/prometheus/releases/download/v3.0.0-beta.1/prometheus-3.0.0-beta.1.linux-amd64.tar.gz
  - sudo tar xvf prometheus-3.0.0-beta.1.linux-amd64.tar.gz
  - sudo groupadd --system prometheus
  - sudo useradd -s /sbin/nologin --system -g prometheus prometheus
  - sudo mkdir /etc/prometheus
  - sudo mkdir /var/lib/prometheus
  - sudo mv prometheus-3.0.0-beta.1.linux-amd64/prometheus /usr/local/bin
  - sudo mv prometheus-3.0.0-beta.1.linux-amd64/promtool /usr/local/bin
  - sudo mv prometheus-3.0.0-beta.1.linux-amd64/consoles /etc/prometheus
  - sudo mv prometheus-3.0.0-beta.1.linux-amd64/console_libraries /etc/prometheus
  - |
    cat <<EOF | sudo tee /etc/prometheus/prometheus.yml
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["0.0.0.0:9090"]

      - job_name: "node"
        static_configs:
          - targets: ["34.235.130.25:9100"]
    EOF
   - |
    cat <<EOF | sudo tee /etc/systemd/system/prometheus.service
    [Unit]
    Description=Prometheus
    Wants=network-online.target
    After=network-online.target

    [Service]
    User=prometheus
    Group=prometheus
    Type=simple
    ExecStart=/usr/local/bin/prometheus \
     --config.file /etc/prometheus/prometheus.yml \
     --storage.tsdb.path /var/lib/prometheus/ \
     --web.console.templates=/etc/prometheus/consoles \
     --web.console.libraries=/etc/prometheus/console_libraries

    [Install]
    WantedBy=multi-user.target
    EOF
  - sudo chown prometheus:prometheus /usr/local/bin/prometheus
  - sudo chown prometheus:prometheus /usr/local/bin/promtool
  - sudo chown -R prometheus:prometheus /etc/prometheus
  - sudo chown -R prometheus:prometheus /var/lib/prometheus
  - sudo systemctl daemon-reload
  - sudo systemctl enable prometheus
  - sudo systemctl start prometheus
  - sudo wget https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
  - sudo tar xzf node_exporter-1.7.0.linux-amd64.tar.gz
  - sudo mv node_exporter-1.7.0.linux-amd64 /etc/node_exporter
  - |
    cat <<EOF | sudo tee /etc/systemd/system/node_exporter.service
    [Unit]
    Description=Node Exporter
    Wants=network-online.target
    After=network-online.target

    [Service]
    ExecStart=/etc/node_exporter/node_exporter
    Restart=always

    [Install]
    WantedBy=multi-user.target
    EOF
  - sudo systemctl daemon-reload
  - sudo systemctl enable node_exporter
  - sudo systemctl start node_exporter

