#cloud-config
users:
  - default
  - name: renggli
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/z0nTUXR51MAQXH+H/hJyoaSkqEV1Xt4aykciSi0NherZfJNm0shgkQf9/+YeCLj3tBsb+iH4FWY+4tPAfNktciYFr8RgCr8u7ejsznT0CRq7SkgOZOyoHfTTY20X44wmvxJHj20nrkudDe6xUDhxxNiYdP0YdIMGCYbcrtilbknZp8o/ojuxGYyIycNMp7GURNno8YpaeaqyeNp4JRjxf70q5H3oNUnwVYs6bmHLApiZY/uFxI4XmOkrMYRcWHMJtmr3CqSb3XGhWQYYRCoSnDU2WCi21D3YFW9ygwyfZqqPHzuSxFy7dJusywMIQ/4jJx0e5sqVhd6QI6335wIYjweAivucehUQVF80rAI4S5A7ZusWRW0b9cxBHdT9/jusPzeSE+k9AwaDGf94Sr5Or31oe+kI52dCWN8LV3T2lcFTmz9MuYskGrUoXSKWVFTV7EEhY1cF9GTiW2vzW0RpJNw633uunVOFZ+He/azvgKMyTq7N62umJFAlfomMSWU= andrin@DESKTOP-9HLUJS2

package_update: true

packages:
  - mysql-client

runcmd:
  - apt-get install -y openjdk-11-jdk
  - wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz -O /tmp/apache-maven-3.9.9-bin.tar.gz 
  - tar xvf /tmp/apache-maven-3.9.9-bin.tar.gz -C /opt 
  - git clone https://gitlab.com/bbwrl/m346-ref-card-03.git 
  - mysql -h db-jokesapp.cogrb9epzmxy.us-east-1.rds.amazonaws.com -u admin -p12345678 -e "DROP DATABASE IF EXISTS jokedb; CREATE DATABASE jokedb; CREATE USER 'jokedbuser' IDENTIFIED BY '123456'; GRANT ALL PRIVILEGES ON jokedb.* TO 'jokedbuser'; FLUSH PRIVILEGES;" # Change DB-Servers endpoint
  - sed -i 's|http://localhost:3000|*|g' m346-ref-card-03/src/main/java/ch/bbw/architecturerefcard03/controller/JokeRestController.java 
  - echo "" > m346-ref-card-03/src/main/resources/application.properties 
  - echo "spring.datasource.url=jdbc:mariadb://db-jokesapp.cogrb9epzmxy.us-east-1.rds.amazonaws.com/jokedb" >> m346-ref-card-03/src/main/resources/application.properties # Change DB-Servers endpoint IMPORTANT!!! add a /jokedb to your endpoint + Change Path if user is not "renggli"
  - echo "spring.datasource.username=jokedbuser" >> m346-ref-card-03/src/main/resources/application.properties 
  - echo "spring.datasource.password=123456" >> m346-ref-card-03/src/main/resources/application.properties 
  - echo "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect" >> m346-ref-card-03/src/main/resources/application.properties 
  - echo "spring.datasource.driver-class-name=org.mariadb.jdbc.Driver" >> m346-ref-card-03/src/main/resources/application.properties 
  - echo "# Datenbankinitialisierung" >> m346-ref-card-03/src/main/resources/application.properties 
  - echo "spring.sql.init.mode=always" >> m346-ref-card-03/src/main/resources/application.properties 
  - bash -c "pushd m346-ref-card-03/ && /opt/apache-maven-3.9.9/bin/mvn package; popd" 
  - mkdir -p /opt/m346-ref-card-03
  - cp m346-ref-card-03/target/architecture-refcard-03-0.0.1-SNAPSHOT.jar /opt/m346-ref-card-03/
  - chown root:renggli /opt/m346-ref-card-03
  - chmod -R 755 /opt/m346-ref-card-03
  - java -DDB_USERNAME="jokedbuser" -DDB_PASSWORD="123456" -jar /opt/m346-ref-card-03/architecture-refcard-03-0.0.1-SNAPSHOT.jar >> /var/log/m346-ref-card-03-log.log
