#cloud-config
users:
  - default
  - name: renggli
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINh7P/fAuzssL5EGVf8WABbU6VOwngCWvFnAoLkeqGP1 taishaku@debian
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGfK+Q8RcGAFlU1/ssU+bGz8ymB0qMxG3HsPtTuTI7r0 andrin@DESKTOP-9HLUJS2

package_update: true 
packages:
  - mysql-client
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - php-json

runcmd:
  - mysql -h wordpress-db.cogrb9epzmxy.us-east-1.rds.amazonaws.com -u admin -p12345678 -e "CREATE USER 'wordpress' IDENTIFIED BY 'password'; GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'; FLUSH PRIVILEGES;"
  - wget https://wordpress.org/latest.tar.gz
  - tar -xzf latest.tar.gz
  - cp wordpress/wp-config-sample.php wordpress/wp-config.php
  - sed -i 's/database_name_here/wordpress/g' wordpress/wp-config.php
  - sed -i 's/username_here/wordpress/g' wordpress/wp-config.php
  - sed -i 's/password_here/password/g' wordpress/wp-config.php
  - sed -i 's/localhost/wordpress-db.cogrb9epzmxy.us-east-1.rds.amazonaws.com/g' wordpress/wp-config.php
  - rm -f /var/www/html/index.html
  - cp -r wordpress/* /var/www/html/
  - apt install php-mysqli

