#cloud-config
users:
  - default
  - name: renggli
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6xIWERIZ7yD6W3niuuJ8S8FMGm3YNy1J1yxLZb+KQjY9hwIEfWJSNDIi6bbKRB0ozo0ca5o4/GBYX/MtBrbvqiQMtviboUtr/vLXvVVuTwf8HIubwySbIEfPqrpqpvQQtzRGu1SaDIm0gmlqqWwV6ppRIdy0AQIQCL9rc8pNh8x/gwzWHKKG16suxvH3j+qD+5Du+/NT7ab1BmHqPMmUK1GId8/oUejVHIiK7mGRERoQwdI8sE1eLVNcCU/NYzvx/jLIqDT1+YKQaLOxkiJViCBttn/1xLvW33fEnuuBjFCpjwFtE3/qGbR4jWlOpWqevI6TLKyEbitWPZRVU0UwWI43vMZp5MRG+QVjx79P7nKf6BjUpuvC/KaWx2lIHz7lBig8hyRv40m9kjHuzEN3Yj5mSbZ/XJhFsT0PuQbk9E8EM0bqtHSpRi+OdDH8nHqbWFd45Q4pON1OwRwq4Gztb8i8+ZvaWGmWEAyvXIEimUB+fsoQPRhc9E4OmxTRnboM= andrin@DESKTOP-9HLUJS2

package_update: true
#package_upgrade: true
packages:
  - apache2
  - php
  - php-mysql
  - wget
  - unzip

runcmd:
  - systemctl start apache2
  - systemctl enable apache2
  - wget https://wordpress.org/latest.zip -P /tmp
  - unzip /tmp/latest.zip -d /var/www/html/
  - mv /var/www/html/wordpress/* /var/www/html/
  - rm -rf /var/www/html/wordpress
  - chown -R www-data:www-data /var/www/html
  - chmod -R 755 /var/www/html
  - cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
  - sed -i "s/database_name_here/wordpress/" /var/www/html/wp-config.php
  - sed -i "s/username_here/wordpressuser/" /var/www/html/wp-config.php
  - sed -i "s/password_here/password/" /var/www/html/wp-config.php

  #- sed -i "s/database_name_here/YOUR_DB_NAME/" /var/www/html/wp-config.php
  #- sed -i "s/username_here/YOUR_DB_USER/" /var/www/html/wp-config.php
  #- sed -i "s/password_here/YOUR_DB_PASSWORD/" /var/www/html/wp-config.php
  #- sed -i "s/localhost/YOUR_RDS_ENDPOINT/" /var/www/html/wp-config.php

